# Site settings
title: Coderica
email: esm1018@gmail.com
description: Erica SM Prenga - Personal blog and portfolio.
# url: "http://127.0.0.1:4000/"
url: "http://coderica.github.io/"
username: coderica
google_plus_username: EricaMarroquinPrenga

# Build settings
markdown: kramdown
